#!/bin/sh

source "$CONFIG_DIR/colors.sh" # Load the colors

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where the plugins are configured

# Variables
FONT_ICONS="Hack Nerd Font"
# FONT="Hack Nerd Font"
FONT="DankMono Nerd Font"
PADDING_L=4
PADDING_R=4
RADIUS=8
POSITION=top
HEIGHT=30
BLUR=10

# Bar Appearance
bar=(
  color=$COLOR_TRANSPARENT			# Bar color
  position=$POSITION          # Bar position
  height=$HEIGHT              # Bar height
  margin=8                    # Overall margin around the bar
  y_offset=4                  # Space b/w top of the screen and the bar
  corner_radius=$RADIUS       # Bar corner radius
  border_width=0              # 0 for no border
  blur_radius=0               # 0 for the full transparency
  padding_left=0
  padding_right=0
  topmost=off                 # Draw the bar over a window and the stock menubar
  #sticky=on                   # Bar stays on when changing workspace
)
sketchybar --bar "${bar[@]}"

# Defaults
default=(
	padding_left=0
  padding_right=0

	background.color=$COLOR_BACKGROUND
  background.border_color=$COLOR_BLUE
  background.border_width=0
  background.corner_radius=$RADIUS
  background.height=$HEIGHT
  background.drawing=off


	icon.font="$FONT_ICONS:Regular:14.24"
  icon.color=$COLOR_FOREGROUND
  icon.highlight_color=$COLOR_PURPLE
  icon.padding_left=$PADDING_L
  icon.padding_right=$PADDING_R
  icon.drawing=on

	label.font="$FONT:Regular:14.24"
  label.color=$COLOR_FOREGROUND
  label.highlight_color=$COLOR_PURPLE
  label.padding_left=$PADDING_L
  label.padding_right=$PADDING_R
  label.drawing=on
)

sketchybar --default "${default[@]}"

# Left Items
source "$ITEM_DIR/logo.sh"
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/left_bar.sh"

# Right Items
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/right_bar.sh"


sketchybar --add event aerospace_workspace_change
sketchybar --add event front_app_switched

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
				--set space.$sid \
				script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "SketchyBar configuration loaded..."
