# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

# DejaVu Sans Mono
# Dank Mono
# Ubuntu Mono
# Space Mono
# VictorMono Nerd Font Mono
# Hack Nerd Font Mono

import = [
	"~/.dotfiles/.config/alacritty/theme.toml",
	"~/.dotfiles/.config/alacritty/keybindings.toml",
]

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 14

[window]
decorations = "full"
opacity = 0.98
dynamic_padding = false

[window.padding]
x = 8
y = 8

